export const SET_BREED = 'SET_BREED'
export const SET_PREV_BREED = 'SET_PREV_BREED'
export const UPDATE_STATUS = 'UPDATE_STATUS'
export const SET_USER_ID = 'SET_USER_ID'
export const SET_FAVORITE = 'SET_FAVORITE'
